services:
  web:
    builds: .
    ports:
      - "5000:80"
    volumes:
      - .:/app
    depends_on:
      - db
    env_files:
      - ./.env
  flask_db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: